import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import './api.dart';

void main() {
  runApp(MaterialApp(
    debugShowCheckedModeBanner: false,
    title: "Meme Generator",
    home: Home(),
  ));
}

class Home extends StatefulWidget {
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  var url = "https://api.imgflip.com/get_memes";

  Autogenerated memData;

  @override
  void initState() {
    super.initState();

    memes();
  }

  memes() async {
    var res = await http.get(url);
    var jsonRes = jsonDecode(res.body);

    memData = Autogenerated.fromJson(jsonRes);
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Meme Genetrator")),
      body: Container(
        child: memData == null
            ? Center(child: CircularProgressIndicator())
            : GridView.count(
                crossAxisCount: 2,
                children: memData.data.memes
                    .map((i) => Card(
                          child: InkWell(
                            onTap: () {
                              Navigator.of(context).push(MaterialPageRoute(
                                  builder: (context) =>
                                      Detail(image: i.url, name: i.name)));
                            },
                            child: Container(
                              decoration: BoxDecoration(
                                  image: DecorationImage(
                                      image: NetworkImage(i.url),
                                      fit: BoxFit.cover)),
                            ),
                          ),
                        ))
                    .toList(),
              ),
      ),
    );
  }
}

class Detail extends StatefulWidget {
  final String image;
  final String name;

  Detail({this.image, this.name});

  @override
  _DetailState createState() => _DetailState();
}

class _DetailState extends State<Detail> {
  String top = '';
  String bottom = '';

  textTop(e) {
    setState(() {
      top = e;
    });
  }

  textBottom(e) {
    setState(() {
      bottom = e;
    });
  }

  Color color = Colors.white;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.name)),
      body: Container(
        child: Column(children: <Widget>[
          Stack(
            alignment: Alignment.topCenter,
            children: <Widget>[
              Container(
                width: MediaQuery.of(context).size.width,
                height: 300.0,
                decoration: BoxDecoration(
                    image: DecorationImage(
                        image: NetworkImage(widget.image),
                        fit: BoxFit.fitWidth)),
              ),
              Positioned(
                top: 10.0,
                bottom: 180.0,
                child: Text(top,
                    style: TextStyle(
                        fontSize: 19.0,
                        fontWeight: FontWeight.bold,
                        color: color)),
              ),
              Positioned(
                top: 250.0,
                bottom: 5.0,
                child: Text(bottom,
                    style: TextStyle(
                        fontSize: 19.0,
                        fontWeight: FontWeight.bold,
                        color: color)),
              )
            ],
          ),
          Row(
            children: <Widget>[
              Flexible(
                child: TextField(
                  onChanged: (e) => textTop(e),
                  decoration: InputDecoration(hintText: "Top Text"),
                ),
              ),
              SizedBox(width: 20.0),
              Flexible(
                child: TextField(
                  onChanged: (e) => textBottom(e),
                  decoration: InputDecoration(hintText: "Bottom Text"),
                ),
              )
            ],
          ),
          SizedBox(height: 20.0),
          Text("Change Color Text :"),
          SizedBox(height: 10.0),
          Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              InkWell(
                onTap: () {
                  setState(() {
                    color = Colors.red;
                  });
                },
                child: ColorWidget(
                  colorq: Colors.red,
                ),
              ),
              InkWell(
                onTap: () {
                  setState(() {
                    color = Colors.yellow;
                  });
                },
                child: ColorWidget(
                  colorq: Colors.yellow,
                ),
              ),
              InkWell(
                onTap: () {
                  setState(() {
                    color = Colors.green;
                  });
                },
                child: ColorWidget(
                  colorq: Colors.green,
                ),
              ),
              InkWell(
                onTap: () {
                  setState(() {
                    color = Colors.blue;
                  });
                },
                child: ColorWidget(
                  colorq: Colors.blue,
                ),
              ),
              InkWell(
                onTap: () {
                  setState(() {
                    color = Colors.white;
                  });
                },
                child: ColorWidget(
                  colorq: Colors.white,
                ),
              ),
              InkWell(
                onTap: () {
                  setState(() {
                    color = Colors.pink;
                  });
                },
                child: ColorWidget(
                  colorq: Colors.pink,
                ),
              ),
            ],
          )
        ]),
      ),
    );
  }
}

class ColorWidget extends StatefulWidget {
  Color colorq;

  ColorWidget({this.colorq});

  @override
  _ColorWidgetState createState() => _ColorWidgetState();
}

class _ColorWidgetState extends State<ColorWidget> {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 60.0,
      height: 60.0,
      color: widget.colorq,
    );
  }
}
